name: Main workflow

on:
push:
    branches:
    - hexo

jobs:
build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10.x
    uses: actions/setup-node@v1
    with:
        node-version: '10.x'
    - name: prepare build env
    env:
        GH_ACTION_DEPLOY_KEY: ${{secrets.GH_ACTION_DEPLOY_KEY}}
        NEXT_VERSION: v7.5.0
    run: |
        mkdir -p ~/.ssh/
        echo "$GH_ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.name 'lichaoran'
        git config --global user.email 'pkwarcraft@gmail.com'
        npm i -g hexo-cli
        npm i
    - name: deploy to github
    env:
        HEXO_ALGOLIA_INDEXING_KEY: ${{secrets.HEXO_ALGOLIA_INDEXING_KEY}}
    run: |
        hexo generate && hexo deploy
