name: Main workflow

on:
  push:
    branches:
    - hexo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js latest
      uses: actions/setup-node@v3
      with:
        node-version: 'latest'
    - name: prepare build env
      env:
        GH_ACTION_DEPLOY_KEY: ${{secrets.GH_ACTION_DEPLOY_KEY}}
      run: |
        mkdir -p ~/.ssh/
        echo "$GH_ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.name 'lichaoran'
        git config --global user.email 'pkwarcraft@gmail.com'
        npm i -g hexo-cli
        npm i
        sed -i 's|https://mywaaagh_admin.gitee.io/blog/|https://pkking.github.io/' _config.yml
        sed -i 's|root: /blog/|root: /|g' _config.yml
    - name: deploy to github
      run: |
        hexo generate && hexo deploy
